steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--tag=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--file=Dockerfile'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=OPENAI_API_KEY=openai-api-key:latest,TWILIO_AUTHTOKEN=twilio-authtoken:latest,TWILIO_ACCOUNTSID=twilio-accountsid:latest,TWILIO_FROM=twilio-from:latest,GOOGLESHEETS_SHEETID=googlesheets-sheetid:latest'
      - '--service-account=$_SERVICE_ACCOUNT'
      - '--max-instances=1'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _AR_HOSTNAME: europe-north1-docker.pkg.dev
  _REPO_NAME: gtj-snooker-scores
  _DEPLOY_REGION: europe-north1
  _IMAGE: $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  _PLATFORM: managed
  _SERVICE_ACCOUNT: snooker-bot@otto-snooker-bot.iam.gserviceaccount.com
  _SERVICE_NAME: gtj-snooker-scores
  _TRIGGER_ID: 8ea18e33-a994-4e69-99e2-0360eb4c330a
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - gtj-snooker-scores
