steps:
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args:
  #     - cp
  #     - gs://otto-snooker-bot_cloudbuild/fewshots_groove.py
  #     - app/llm/fewshots_groove.py
  #   id: Copy fewshots_groove.py
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--tag=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID'
      - '--file=Dockerfile'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$BUILD_ID,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--set-env-vars=NODE_ENV=$_NODE_ENV'  # SET TOURNAMENT TYPE
      - '--set-secrets=TWILIO_AUTHTOKEN=twilio-authtoken:latest,TWILIO_ACCOUNTSID=twilio-accountsid:latest,TWILIO_FROM=twilio-from:latest,SNOOKER_API_SECRET=SNOOKER_API_SECRET:latest'
      - '--service-account=$_SERVICE_ACCOUNT'
      - '--max-instances=1'
      - '--quiet'
    entrypoint: gcloud
      # Then, update the traffic to point to the latest revision
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update-traffic
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--region=$_DEPLOY_REGION'
      - '--to-latest'
    entrypoint: gcloud
    id: Deploy
images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _NODE_ENV: PROD
  _AR_HOSTNAME: europe-north1-docker.pkg.dev
  _REPO_NAME: gtj-snooker-scores
  _DEPLOY_REGION: europe-north1
  _IMAGE: $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID
  _PLATFORM: managed
  _SERVICE_ACCOUNT: snooker-bot@otto-snooker-bot.iam.gserviceaccount.com
  _SERVICE_NAME: gtj-snooker-scores
  _TRIGGER_ID: 8ea18e33-a994-4e69-99e2-0360eb4c330a
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - gtj-snooker-scores
